-- Baseline snapshot of the LIVE schema for project "recipe-os" (tnznfkgrghgyyxlihwkf).
-- Rewritten 2026-08-17 to replace a stale hand-written draft that no longer matched
-- the live database (wrong table/column names, missing ~19 tables). This file was
-- generated by introspecting the live project directly (tables, columns, defaults,
-- checks, FKs, triggers, functions, RLS policies) via the Supabase MCP tools, not by
-- guessing. Treat it as a snapshot baseline, not a hand-authored migration.
--
-- Known gap carried over intentionally: RLS is disabled on 11 tables live
-- (households, household_members, push_subscriptions, notification_preferences,
-- pantry_check_ins, pantry_check_in_responses, recipe_ingredients, recipe_steps,
-- recipe_nutrition, ingredient_shelf_life, ingredient_substitutions), and three
-- tables with RLS enabled (collection_recipes, meal_plan_slots, shopping_list_items)
-- have no policies defined at all. This migration reproduces that state as-is rather
-- than silently fixing it — see the security advisory raised alongside this change.

create extension if not exists "uuid-ossp" with schema extensions;
create extension if not exists pgcrypto with schema extensions;

-- ============================================================================
-- Functions
-- ============================================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  generated_username text;
begin
  -- Generate username from email as safe fallback
  generated_username := coalesce(
    new.raw_user_meta_data->>'username',
    regexp_replace(
      split_part(new.email, '@', 1),
      '[^a-zA-Z0-9_]', '_', 'g'
    ),
    'user_' || substr(new.id::text, 1, 8)
  );

  insert into public.user_profiles(
    id, username, full_name)
  values(
    new.id,
    generated_username,
    coalesce(
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'name',
      split_part(new.email, '@', 1)
    )
  )
  on conflict (id) do nothing;

  insert into public.user_health_profiles(user_id)
  values(new.id)
  on conflict (user_id) do nothing;

  insert into public.notification_preferences(user_id)
  values(new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

-- ============================================================================
-- Tables
-- ============================================================================

create table if not exists public.user_profiles (
  id uuid primary key references auth.users (id),
  username text unique,
  full_name text,
  avatar_url text,
  bio text,
  household_id uuid,
  tier text default 'free' check (tier = any (array['free', 'pro', 'family'])),
  tier_expires_at timestamptz,
  username_changed_at timestamptz,
  onboarding_completed boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  diet_type text,
  allergies text[] default '{}',
  health_goals text,
  measurement_units text,
  default_servings integer
);

create table if not exists public.user_health_profiles (
  id uuid primary key default extensions.uuid_generate_v4(),
  user_id uuid unique references auth.users (id),
  diet_type text default 'none',
  allergies text[] default '{}',
  health_goals text default 'balanced',
  activity_level text default 'moderate',
  daily_calorie_target integer,
  measurement_units text default 'metric',
  default_servings integer default 2,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.households (
  id uuid primary key default extensions.uuid_generate_v4(),
  name text not null,
  owner_id uuid references auth.users (id),
  invite_code text unique,
  max_members integer default 5,
  created_at timestamptz default now()
);

create table if not exists public.household_members (
  id uuid primary key default extensions.uuid_generate_v4(),
  household_id uuid references public.households (id),
  user_id uuid references auth.users (id),
  role text default 'member' check (role = any (array['owner', 'admin', 'member'])),
  joined_at timestamptz default now()
);

create table if not exists public.push_subscriptions (
  id uuid primary key default extensions.uuid_generate_v4(),
  user_id uuid references auth.users (id),
  expo_push_token text not null,
  device_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.notification_preferences (
  id uuid primary key default extensions.uuid_generate_v4(),
  user_id uuid unique references auth.users (id),
  expiry_alerts boolean default true,
  meal_reminders boolean default true,
  recipe_suggestions boolean default false,
  quiet_hours_start time default '22:00:00',
  quiet_hours_end time default '07:00:00',
  max_per_day integer default 2,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.pantry_items (
  id uuid primary key default extensions.uuid_generate_v4(),
  user_id uuid references auth.users (id),
  household_id uuid references public.households (id),
  name text not null,
  category text default 'other',
  quantity numeric not null default 1,
  unit text default 'pcs',
  storage_location text default 'pantry',
  expiry_date date,
  expiry_type text default 'estimated' check (expiry_type = any (array['exact', 'estimated'])),
  barcode text,
  status text default 'available' check (status = any (array['available', 'low', 'finished', 'expired'])),
  add_method text default 'manual' check (add_method = any (array['snap', 'barcode', 'voice', 'manual'])),
  last_confirmed_at timestamptz,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.pantry_check_ins (
  id uuid primary key default extensions.uuid_generate_v4(),
  user_id uuid references auth.users (id),
  triggered_by text,
  items_reviewed integer default 0,
  completed_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.pantry_check_in_responses (
  id uuid primary key default extensions.uuid_generate_v4(),
  check_in_id uuid references public.pantry_check_ins (id),
  pantry_item_id uuid references public.pantry_items (id),
  response text check (response = any (array['still_have', 'used_up', 'threw_away'])),
  created_at timestamptz default now()
);

create table if not exists public.recipes (
  id uuid primary key default extensions.uuid_generate_v4(),
  title text not null,
  description text,
  cuisine_type text,
  meal_type text[],
  diet_tags text[] default '{}',
  difficulty text default 'medium' check (difficulty = any (array['easy', 'medium', 'hard'])),
  prep_time_mins integer,
  cook_time_mins integer,
  total_time_mins integer,
  default_servings integer default 2,
  equipment text[] default '{}',
  image_urls text[] default '{}',
  source_url text,
  is_user_generated boolean default false,
  created_by uuid references auth.users (id),
  view_count integer default 0,
  save_count integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.recipe_ingredients (
  id uuid primary key default extensions.uuid_generate_v4(),
  recipe_id uuid references public.recipes (id),
  name text not null,
  quantity numeric,
  unit text,
  notes text,
  is_optional boolean default false,
  sort_order integer default 0
);

create table if not exists public.recipe_steps (
  id uuid primary key default extensions.uuid_generate_v4(),
  recipe_id uuid references public.recipes (id),
  step_number integer not null,
  instruction text not null,
  tip text,
  duration_mins integer,
  created_at timestamptz default now()
);

create table if not exists public.recipe_nutrition (
  id uuid primary key default extensions.uuid_generate_v4(),
  recipe_id uuid unique references public.recipes (id),
  calories_per_serving numeric,
  protein_g numeric,
  carbs_g numeric,
  fat_g numeric,
  fiber_g numeric,
  sugar_g numeric,
  sodium_mg numeric,
  generated_by text default 'ai',
  generated_at timestamptz default now()
);

create table if not exists public.saved_recipes (
  id uuid primary key default extensions.uuid_generate_v4(),
  user_id uuid references auth.users (id),
  recipe_id uuid references public.recipes (id),
  collection_id uuid,
  saved_at timestamptz default now()
);

create table if not exists public.collections (
  id uuid primary key default extensions.uuid_generate_v4(),
  user_id uuid references auth.users (id),
  name text not null,
  description text,
  cover_image_url text,
  is_default boolean default false,
  created_at timestamptz default now()
);

-- Note: saved_recipes.collection_id has no FK constraint live (verified via
-- introspection) even though collections exists — reproduced as-is, not added.

create table if not exists public.collection_recipes (
  id uuid primary key default extensions.uuid_generate_v4(),
  collection_id uuid references public.collections (id),
  recipe_id uuid references public.recipes (id),
  added_at timestamptz default now()
);

create table if not exists public.cook_logs (
  id uuid primary key default extensions.uuid_generate_v4(),
  user_id uuid references auth.users (id),
  recipe_id uuid references public.recipes (id),
  servings_cooked integer,
  rating integer check (rating >= 1 and rating <= 5),
  is_favourite boolean default false,
  notes text,
  completed_at timestamptz default now(),
  created_at timestamptz default now()
);

create table if not exists public.meal_plans (
  id uuid primary key default extensions.uuid_generate_v4(),
  user_id uuid references auth.users (id),
  household_id uuid references public.households (id),
  week_start date not null,
  generated_by text default 'manual' check (generated_by = any (array['manual', 'ai'])),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.meal_plan_slots (
  id uuid primary key default extensions.uuid_generate_v4(),
  meal_plan_id uuid references public.meal_plans (id),
  recipe_id uuid references public.recipes (id),
  slot_date date not null,
  meal_type text not null check (meal_type = any (array['breakfast', 'lunch', 'dinner', 'snack'])),
  servings integer default 2,
  created_at timestamptz default now()
);

create table if not exists public.shopping_lists (
  id uuid primary key default extensions.uuid_generate_v4(),
  user_id uuid references auth.users (id),
  household_id uuid references public.households (id),
  name text default 'My Shopping List',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.shopping_list_items (
  id uuid primary key default extensions.uuid_generate_v4(),
  shopping_list_id uuid references public.shopping_lists (id),
  recipe_id uuid references public.recipes (id),
  name text not null,
  quantity numeric,
  unit text,
  category text,
  is_checked boolean default false,
  source text default 'manual' check (source = any (array['manual', 'recipe', 'pantry'])),
  sort_order integer default 0,
  created_at timestamptz default now()
);

create table if not exists public.notifications (
  id uuid primary key default extensions.uuid_generate_v4(),
  user_id uuid references auth.users (id),
  type text not null,
  title text not null,
  body text not null,
  data jsonb,
  is_read boolean default false,
  sent_at timestamptz default now()
);

create table if not exists public.ingredient_shelf_life (
  id uuid primary key default extensions.uuid_generate_v4(),
  ingredient_name text not null,
  category text,
  fridge_days integer,
  freezer_days integer,
  pantry_days integer,
  notes text
);

create table if not exists public.ingredient_substitutions (
  id uuid primary key default extensions.uuid_generate_v4(),
  ingredient_name text not null,
  substitute_name text not null,
  ratio text,
  notes text,
  works_for text[]
);

-- ============================================================================
-- Triggers
-- ============================================================================

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

-- ============================================================================
-- Row Level Security
-- Enabled/disabled state and policies below mirror the LIVE project exactly as
-- introspected. Tables not listed here have RLS disabled live (see header note).
-- ============================================================================

alter table public.user_profiles enable row level security;
alter table public.user_health_profiles enable row level security;
alter table public.pantry_items enable row level security;
alter table public.recipes enable row level security;
alter table public.saved_recipes enable row level security;
alter table public.collections enable row level security;
alter table public.collection_recipes enable row level security;
alter table public.cook_logs enable row level security;
alter table public.meal_plans enable row level security;
alter table public.meal_plan_slots enable row level security;
alter table public.shopping_lists enable row level security;
alter table public.shopping_list_items enable row level security;
alter table public.notifications enable row level security;

-- Note: collection_recipes, meal_plan_slots, shopping_list_items have RLS
-- enabled live but currently have NO policies attached (so all anon/authenticated
-- access is denied, only service_role bypasses). Reproduced as-is, not fixed here.

drop policy if exists "Users can view own profile" on public.user_profiles;
create policy "Users can view own profile"
on public.user_profiles for select
using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.user_profiles;
create policy "Users can insert own profile"
on public.user_profiles for insert
with check (auth.uid() = id);

drop policy if exists "Service role can insert profiles" on public.user_profiles;
create policy "Service role can insert profiles"
on public.user_profiles for insert
to service_role
with check (true);

drop policy if exists "Users can update own profile" on public.user_profiles;
create policy "Users can update own profile"
on public.user_profiles for update
using (auth.uid() = id);

drop policy if exists "Users can manage own health profile" on public.user_health_profiles;
create policy "Users can manage own health profile"
on public.user_health_profiles for all
using (auth.uid() = user_id);

drop policy if exists "Users can insert own health profile" on public.user_health_profiles;
create policy "Users can insert own health profile"
on public.user_health_profiles for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can manage own pantry" on public.pantry_items;
create policy "Users can manage own pantry"
on public.pantry_items for all
using (auth.uid() = user_id);

drop policy if exists "Recipes are viewable by everyone" on public.recipes;
create policy "Recipes are viewable by everyone"
on public.recipes for select
using (true);

drop policy if exists "Users can create recipes" on public.recipes;
create policy "Users can create recipes"
on public.recipes for insert
with check (auth.uid() = created_by);

drop policy if exists "Users can manage own saved recipes" on public.saved_recipes;
create policy "Users can manage own saved recipes"
on public.saved_recipes for all
using (auth.uid() = user_id);

drop policy if exists "Users can manage own collections" on public.collections;
create policy "Users can manage own collections"
on public.collections for all
using (auth.uid() = user_id);

drop policy if exists "Users can manage own cook logs" on public.cook_logs;
create policy "Users can manage own cook logs"
on public.cook_logs for all
using (auth.uid() = user_id);

drop policy if exists "Users can manage own meal plans" on public.meal_plans;
create policy "Users can manage own meal plans"
on public.meal_plans for all
using (auth.uid() = user_id);

drop policy if exists "Users can manage own shopping lists" on public.shopping_lists;
create policy "Users can manage own shopping lists"
on public.shopping_lists for all
using (auth.uid() = user_id);

drop policy if exists "Users can view own notifications" on public.notifications;
create policy "Users can view own notifications"
on public.notifications for select
using (auth.uid() = user_id);

-- notification_preferences has RLS disabled live, but this one insert policy
-- exists (inert while RLS stays off) — reproduced for fidelity, not activated.
drop policy if exists "Users can insert own notification prefs" on public.notification_preferences;
create policy "Users can insert own notification prefs"
on public.notification_preferences for insert
with check (auth.uid() = user_id);
